// Code generated by cqgen, DO NOT EDIT.
// +build !websocket

package core

/*
#include <stdint.h>
extern char* GO_Create(char* version);
extern int GO_Event(char* botQQ, int msgType, int subType, char* sourceId, char* activeQQ, char* passiveQQ, char* msg, char* msgNum, char* msgId, char* rawMsg, char* timeStamp, char* retText);
extern int GO_SetUp();
extern int GO_DestroyPlugin();

extern char* __stdcall XQ_Create(char* version);
extern int __stdcall XQ_Event(char* botQQ, int msgType, int subType, char* sourceId, char* activeQQ, char* passiveQQ, char* msg, char* msgNum, char* msgId, char* rawMsg, char* timeStamp, char* retText);
extern int __stdcall XQ_SetUp();
extern int __stdcall XQ_DestroyPlugin();

char* _stdcall XQ_Create(char* version)
{
	return GO_Create(version);
}

int _stdcall XQ_Event(char* botQQ, int msgType, int subType, char* sourceId, char* activeQQ, char* passiveQQ, char* msg, char* msgNum, char* msgId, char* rawMsg, char* timeStamp, char* retText)
{
	return GO_Event(botQQ, msgType, subType, sourceId, activeQQ, passiveQQ, msg, msgNum, msgId, rawMsg, timeStamp, retText);
}

int _stdcall XQ_SetUp()
{
	return GO_DestroyPlugin();
}

int _stdcall XQ_DestroyPlugin()
{
	return GO_SetUp();
}
*/
import "C"
